/**
 * REGENT — distilled citation index from the CMU MBA corpus (metadata only).
 * Generated by regent/build_corpus_index.py from /Users/nick/CMU. Each course lists
 * real readings / working models so executive recommendations cite a verifiable source.
 * Regenerate: `python3 build_corpus_index.py` then re-distill. Do not hand-edit titles.
 */

export interface CorpusCourse {
  course: string;
  readings: string[];
  models: string[];
}

export const CORPUS_INDEX: Record<string, CorpusCourse> = {
  'finance i': {
    course: 'Finance I',
    readings: [],
    models: [],
  },
  'finance ii': {
    course: 'Finance II',
    readings: ['slides5 M', 'slides5 O', 'slides5'],
    models: ['Data-AMZN', 'Regression'],
  },
  'funding early stage ventures': {
    course: 'Funding Early-Stage Ventures',
    readings: [
      'Valuations Presentation 11.6.24 - ZM',
      'Trendsetter Feedback',
      'BlueTree - Investors Perspective - CMU 11.13. 2024',
    ],
    models: ['Small Piece-Big Pie Charts master', 'Trendsetter 2-antidilution answer'],
  },
  'investment analysis': {
    course: 'Investment Analysis',
    readings: [
      '2024.07.06 Portfolio Risk and the Weighted Average of Individual Asset Risks',
      '2025.03.10 Class 1 Discussion Part 1',
      'TIFF (2021) Private Equity Primer',
    ],
    models: [],
  },
  'venture capital and the finance of innovation': {
    course: 'Venture Capital & the Finance of Innovation',
    readings: ['Week 7', 'Week 7 Notes', 'Week 6'],
    models: ['VC Method', 'CMU Dash Valuation'],
  },
  'financial and managerial accounting i': {
    course: 'Financial & Managerial Accounting I',
    readings: [
      '6. DS in Class Review of SCF',
      '02.1 Receivables Review (for in class session)',
      '02. Carnegie Laundry Corporation (UPDATED)',
    ],
    models: ['06. SCF Practice Problem Data'],
  },
  'financial and managerial accounting ii': {
    course: 'Financial & Managerial Accounting II',
    readings: [
      '02 DS 2b Intro to Short-term Decision Problems',
      'DS 3. Pre Class Assignment Solutuions',
      '03 STDM Post Assignment (Solution)',
    ],
    models: ['04. Waltham Motors Tables Student', '04.Berkshire Toy Co Student'],
  },
  'strategy performance measurement and corporate governance': {
    course: 'Strategy, Performance Measurement & Corporate Governance',
    readings: [
      'DS 2. Own Versus Competitor Costs',
      'DS 4 Incentive Theory Moral Hazard',
      'DS 5 Divisional Performance Evaluation',
    ],
    models: ['DS 5 Vyaderm (EVA) Data'],
  },
  'corporate strategy': {
    course: 'Corporate Strategy',
    readings: [],
    models: [],
  },
  'marketing management': {
    course: 'Marketing Management',
    readings: ['long and short term impact of social media firestorms'],
    models: [],
  },
  'pricing strategy': {
    course: 'Pricing Strategy',
    readings: ['Textbook Chapter2', 'Bistro Pricing Game Hybrid', 'PricingStrategy EVC'],
    models: ['SalesAdsData', 'OrangeJuiceExample'],
  },
  'analytical marketing': {
    course: 'Analytical Marketing',
    readings: [],
    models: [],
  },
  'marketing research': {
    course: 'Marketing Research',
    readings: [
      'Marketing Research An Aid to Decision Making POST',
      'Intro to SPSS Continued',
      'Intro to SPSS Continued - PRE CLASS',
    ],
    models: ['multiple comparison simulation'],
  },
  'design for digital services': {
    course: 'Design for Digital Services',
    readings: [
      'SD - OH1- Good Services, Rethink Users + User Journey Map',
      'SD - OH2- Digital Design Fundamentals',
      'SD - OH3 - Final thoughts',
    ],
    models: [],
  },
  'operations management': {
    course: 'Operations Management',
    readings: [
      'Module4-ProductionPlanning-Technical',
      'the-digital-future-of-manufacturing-consumer-packaged-goods-2021',
      'ited.2019.0216cs (Crayon Production)',
    ],
    models: [],
  },
  'sustainable operations': {
    course: 'Sustainable Operations',
    readings: ['Unit 5A Notes 2026', 'Unit 5S Notes 2026', 'Unit 5A Notes 2026 Annotated'],
    models: ['SCM Convolution (1)', 'Matrix Mult'],
  },
  optimization: {
    course: 'Optimization',
    readings: [],
    models: [],
  },
  'statistical decision making': {
    course: 'Statistical Decision Making',
    readings: [
      'S7 Simple Regression Hypothesis Testing & Prediction',
      'S4 Statistical Quality Control',
      'S1 Understanding & Calculating Quantiles',
    ],
    models: ['PredDat', 'PPS1 Individual Q1'],
  },
  'end to end business analytics': {
    course: 'End-to-End Business Analytics',
    readings: [],
    models: [],
  },
  'ethics and leadership': {
    course: 'Ethics and Leadership',
    readings: [],
    models: [],
  },
  'managing networks and organizations': {
    course: 'Managing Networks and Organizations',
    readings: [
      '01 Intro&Collective Exchange Circle 2024 PTOH',
      '2 IntroClass 2024 FINAL',
      'Organizational-Culture-The-Key-to-Success',
    ],
    models: [],
  },
  'managing people and teams': {
    course: 'Managing People and Teams',
    readings: [],
    models: [],
  },
  negotiations: {
    course: 'Negotiations',
    readings: [
      'Cartoon Plan Exemplary Buyers',
      'Plan 3 Cartoon - exemplary plan sellers',
      '7 Team Conflict and Multiparty Negotiation 2025',
    ],
    models: [],
  },
  'global and distributed teams': {
    course: 'Global and Distributed Teams',
    readings: [
      'Session 02 Team Comp Eurofin GDT 2025',
      'Leung Cohen 2011 Within-and between-culture variation',
      'session 03 Collaboration in GDTeams 2025',
    ],
    models: [],
  },
  'executive communication skills': {
    course: 'Executive Communication Skills',
    readings: [],
    models: [],
  },
};
