-- Seed baseline tool capability catalog inferred from current edge function surfaces.
-- Idempotent upsert keyed by tool_id so this migration can be re-applied safely.

INSERT INTO public.tool_capabilities (
  tool_id,
  name,
  capability_tags,
  mode,
  approval_policy,
  role_requirements,
  connector_dependencies,
  blast_radius,
  fallback_mode
)
VALUES
  ('edge.eigen-tool-capabilities.read','Eigen capability registry read','["eigen","eigenx","registry"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-tool-capabilities.write','Eigen capability registry write','["eigen","eigenx","registry"]'::jsonb,'write'::tool_mode,'admin_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','none'),
  ('edge.eigen-chat.write','Eigen authenticated chat','["eigen","eigenx","chat"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','deny'),
  ('edge.eigen-chat-public.write','Eigen public chat','["eigen","eigen_public","chat"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'[]'::jsonb,'[]'::jsonb,'medium','deny'),
  ('edge.eigen-widget-session.write','Eigen widget session issue','["eigen","eigenx","widget"]'::jsonb,'write'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.eigen-widget-chat.write','Eigen widget chat','["eigen","eigenx","widget","chat"]'::jsonb,'write'::tool_mode,'none_required'::approval_policy,'[]'::jsonb,'[]'::jsonb,'medium','deny'),
  ('edge.eigen-retrieve.read','Eigen retrieval query','["eigen","eigenx","retrieve"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-source-inventory.read','Eigen source inventory','["eigen","eigenx","inventory"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-public-sources.read','Eigen public sources','["eigen","eigen_public","inventory"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'[]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-ingest.write','Eigen ingest documents','["eigen","eigenx","ingest"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.eigen-fetch-ingest.write','Eigen fetch and ingest','["eigen","eigen_public","ingest"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.eigen-memory-entries.read','Eigen memory read','["eigen","eigenx","memory"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-memory-entries.write','Eigen memory write','["eigen","eigenx","memory"]'::jsonb,'write'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.eigen-knowledge-chunks.read','Eigen knowledge chunks read','["eigen","eigenx","knowledge"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-knowledge-chunks.write','Eigen knowledge chunks write','["eigen","eigenx","knowledge"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.eigen-retrieval-runs.read','Eigen retrieval runs read','["eigen","eigenx","retrieval"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.eigen-retrieval-runs.write','Eigen retrieval runs write','["eigen","eigenx","retrieval"]'::jsonb,'write'::tool_mode,'none_required'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.eigen-oracle-outbox-drain.write','Eigen oracle outbox drain','["eigen","oracle","pipeline"]'::jsonb,'write'::tool_mode,'admin_approval'::approval_policy,'["service_role"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-theses.read','Oracle theses read','["oracle","thesis"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','published_scope'),
  ('edge.oracle-theses.write','Oracle theses write','["oracle","thesis"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-evidence-items.read','Oracle evidence read','["oracle","evidence"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.oracle-evidence-items.write','Oracle evidence write','["oracle","evidence"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-signals.read','Oracle signals read','["oracle","signals"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','published_scope'),
  ('edge.oracle-signals.write','Oracle signals write','["oracle","signals"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-read-models.read','Oracle read models','["oracle","read_models"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.oracle-source-packs.read','Oracle source packs read','["oracle","source_packs"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.oracle-source-packs.write','Oracle source packs write','["oracle","source_packs"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-thesis-evidence-links.read','Oracle thesis-evidence links read','["oracle","links"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.oracle-thesis-evidence-links.write','Oracle thesis-evidence links write','["oracle","links"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.oracle-whitespace-runs.read','Oracle whitespace runs read','["oracle","whitespace"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.oracle-whitespace-runs.write','Oracle whitespace runs write','["oracle","whitespace"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.meg-entities.read','MEG entities read','["meg","entities"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.meg-entities.write','MEG entities write','["meg","entities"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.meg-entity-aliases.read','MEG aliases read','["meg","aliases"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.meg-entity-aliases.write','MEG aliases write','["meg","aliases"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.meg-entity-edges.read','MEG edges read','["meg","edges"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.meg-entity-edges.write','MEG edges write','["meg","edges"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.foundation-documents.read','Foundation documents read','["foundation","documents"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.foundation-documents.write','Foundation documents write','["foundation","documents"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.foundation-asset-registry.read','Foundation asset registry read','["foundation","assets"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.foundation-asset-registry.write','Foundation asset registry write','["foundation","assets"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-entities.read','Charter entities read','["charter","entities"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-entities.write','Charter entities write','["charter","entities"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-rights.read','Charter rights read','["charter","rights"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-rights.write','Charter rights write','["charter","rights"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-obligations.read','Charter obligations read','["charter","obligations"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-obligations.write','Charter obligations write','["charter","obligations"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-evidence.read','Charter evidence read','["charter","evidence"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-evidence.write','Charter evidence write','["charter","evidence"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-payouts.read','Charter payouts read','["charter","payouts"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.charter-payouts.write','Charter payouts write','["charter","payouts"]'::jsonb,'write'::tool_mode,'admin_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-decisions.read','Charter decisions read','["charter","decisions"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-decisions.write','Charter decisions write','["charter","decisions"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-governance.read','Charter governance read','["charter","governance"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'low','none'),
  ('edge.charter-governance.write','Charter governance write','["charter","governance"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-provenance.write','Charter provenance write','["charter","provenance"]'::jsonb,'write'::tool_mode,'user_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-asset-valuations.read','Charter asset valuations read','["charter","valuations"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.charter-asset-valuations.write','Charter asset valuations write','["charter","valuations"]'::jsonb,'write'::tool_mode,'admin_approval'::approval_policy,'["operator"]'::jsonb,'[]'::jsonb,'high','deny'),
  ('edge.charter-audit-read.read','Charter audit read','["charter","audit"]'::jsonb,'read'::tool_mode,'user_approval'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.charter-roles.read','Charter role assignments read','["charter","rbac"]'::jsonb,'read'::tool_mode,'none_required'::approval_policy,'["member"]'::jsonb,'[]'::jsonb,'medium','none'),
  ('edge.charter-roles.write','Charter role assignments write','["charter","rbac"]'::jsonb,'write'::tool_mode,'admin_approval'::approval_policy,'["admin"]'::jsonb,'[]'::jsonb,'high','deny')
ON CONFLICT (tool_id) DO UPDATE
SET
  name = EXCLUDED.name,
  capability_tags = EXCLUDED.capability_tags,
  mode = EXCLUDED.mode,
  approval_policy = EXCLUDED.approval_policy,
  role_requirements = EXCLUDED.role_requirements,
  connector_dependencies = EXCLUDED.connector_dependencies,
  blast_radius = EXCLUDED.blast_radius,
  fallback_mode = EXCLUDED.fallback_mode,
  updated_at = now();
